### PR TITLE
Josiahc.performance

### PR DESCRIPTION
**Pull request by Jbcampbe**
This branch shouldn't have gotten so big. I should have been merging these things into develop along the way. But as it is we have a big bunch of changes (a lot of them focused on the add page).

- converted default html dropdowns and date pickers on the add page to some third party ember components I found.

- using Ember-CP validation instead of jquery validate

- made some progress towards moving away from a ton of jquery ajax calls towards Ember Data (and trying to limit the number of requests made)

- upgrade ember-cli version

### CODE REVIEW

**Comment by Jbcampbe** [comment]
NOTE: the ability to limit the number of requests requires a backend change. The code is currently pointing at a version of the api that will allow this but the api code is.... lacking design. The develop api should be updated before we merge this

**Comment by Jbcampbe** [comment]
also some of the css things might not be perfect. However if they are fixed in `release` then `develop` will pick up those changes when we merge `release` back into `develop`

**Comment by ekraihan** [comment]
@Jbcampbe Why is this pointed at develop, not release?

**Comment by Jbcampbe** [comment]
@ekraihan these things should probably be tested more before they are released. Seemed like it would be good to release most of this as `2.2.0` or `3.0.0`. If some of these are stuff we want right away we can cherry pick the commits up into the release branch.

**Comment by Jbcampbe** [comment]
good catch. addressed

**Comment by ekraihan** [comment]
@Jbcampbe 
• I am able to enter invalid characters for model number and serial number. (eg. $, %, etc.) 
• I can enter garbage into the Purchase Date field and it seems to accept it
• Question: Is the upper bound for "year of manufacture" hardcoded or dynamic?

**Comment by Jbcampbe** [comment]
Answer: upper bound in dynamic

**Comment by Jbcampbe** [comment]
@ekraihan any objections to this merging?

**Comment by ekraihan** [comment]
Merge it!

**Pull request merged**
