### PR TITLE
Josiahc.#82 fix datepicker

### PR DESCRIPTION
**Pull request by Jbcampbe**
`<input type='date'>` has only spotty support (especially on safari). Switching to use ember-pikaday component.

### CODE REVIEW

**Comment by Jbcampbe** [comment]
Note this is merging into my other PR. that way I can deploy it to azure and we can test mobile performance before merging to release

**Comment by ekraihan** [comment]
@Jbcampbe @amenders I'm concerned about how small the dates to click are on the date picker

**Comment by ekraihan** [comment]
@Jbcampbe @amenders also, from a styling standpoint, the outline of the date box is now slightly different than the other boxes

**Comment by Jbcampbe** [comment]
@ekraihan so are you wanting to make them bigger? or something else?

**Comment by ekraihan** [comment]
Yea, something like that. We’ve just been shooting for big buttons for the foremen, so I was going with that spirit. But if this is a good MVP, we can just go with it. I looks good though!

Elias Kraihanzel
(317) 225-3413
ekraihan@umail.iu.edu

**Comment by ekraihan** [comment]
@Jbcampbe did you see my styling note above? Also, I just wanted you to be aware how the year picker looks on the iPhone, if you didn't already know:

img_9214

And then, when you pick a year, the phone stays zoomed in. Maybe this can be resolved by turning off zooming.

**Comment by amenders** [comment]
Strange @ekraihan That's not how it renders on my phone. Could be a 5s. vs. larger screen size. I can disable zooming, too, btw.

**Pull request merged**
